### ISSUE TITLE
New issue on moveit.launch.py

### ISSUE THREAD

**Issue by emarca96** [emarca96/franka_mover#3]
ciao @matteodv99tn ,
avvio un'altra issue perchè ho notato una discrepanza sui log del file di lancio movet.launch.py e quello che realmente viene pubblicato sul topic /franka/joint_states.
se avvi il file di lancio di moveit:
```go
ros2 launch franka_fr3_moveit_config moveit.launch.py robot_ip:=dont-care use_fake_hardware:=true
``` 
Quando si fa il planning e poi l'execute, tutto sembra funzionare, a parte casi sporadici, e il log dell'execute è di questo tipo:
```
[rviz2-1] [INFO] [1733925077.438738424] [moveit_ros_visualization.motion_planning_frame]: MoveGroup namespace changed: / -> . Reloading params.
[rviz2-1] [INFO] [1733925077.571844519] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[rviz2-1] [INFO] [1733925077.572640123] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[rviz2-1] [INFO] [1733925077.582959996] [interactive_marker_display_100844110761840]: Connected on namespace: /rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic
[rviz2-1] [INFO] [1733925077.591693797] [moveit_ros_visualization.motion_planning_frame]: group fr3_manipulator
[rviz2-1] [INFO] [1733925077.591732508] [moveit_ros_visualization.motion_planning_frame]: Constructing new MoveGroup connection for group 'fr3_manipulator' in namespace ''
[rviz2-1] [INFO] [1733925077.603877806] [move_group_interface]: Ready to take commands for planning group fr3_manipulator.
[rviz2-1] [INFO] [1733925077.751948448] [interactive_marker_display_100844110761840]: Sending request for interactive markers
[rviz2-1] [INFO] [1733925077.835405444] [interactive_marker_display_100844110761840]: Service response received for initialization
[move_group-3] [INFO] [1733925080.454946791] [moveit_move_group_default_capabilities.move_action_capability]: Received request
[move_group-3] [INFO] [1733925080.455178534] [moveit_move_group_default_capabilities.move_action_capability]: executing..
[rviz2-1] [INFO] [1733925080.455193501] [move_group_interface]: Plan and Execute request accepted
[move_group-3] [INFO] [1733925080.467648470] [moveit_move_group_default_capabilities.move_action_capability]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[move_group-3] [INFO] [1733925080.467838417] [moveit_ros.plan_execution]: Planning attempt 1 of at most 1
[move_group-3] [INFO] [1733925080.467864057] [moveit_move_group_capabilities_base.move_group_capability]: Using planning pipeline 'move_group'
[move_group-3] [INFO] [1733925080.469033775] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'fr3_manipulator' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[move_group-3] [WARN] [1733925080.488006909] [moveit_trajectory_processing.time_optimal_trajectory_generation]: Joint acceleration limits are not defined. Using the default 1 rad/s^2. You can define acceleration limits in the URDF or joint_limits.yaml.
[move_group-3] [INFO] [1733925080.493602736] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-3] [INFO] [1733925080.493630766] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-3] [INFO] [1733925080.493710030] [moveit_ros.trajectory_execution_manager]: Validating trajectory with allowed_start_tolerance 0.01
[move_group-3] [INFO] [1733925080.501245538] [moveit_ros.trajectory_execution_manager]: Starting trajectory execution ...
[move_group-3] [INFO] [1733925080.501285972] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-3] [INFO] [1733925080.501303111] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-3] [INFO] [1733925080.501424643] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: sending trajectory to fr3_arm_controller
[ros2_control_node-4] [INFO] [1733925080.501784964] [fr3_arm_controller]: Received new action goal
[ros2_control_node-4] [INFO] [1733925080.501845169] [fr3_arm_controller]: Accepted new action goal
[move_group-3] [INFO] [1733925080.502042141] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: fr3_arm_controller started execution
[move_group-3] [INFO] [1733925080.502121488] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Goal request accepted!
[ros2_control_node-4] [INFO] [1733925084.733622950] [fr3_arm_controller]: Goal reached, success!
[move_group-3] [INFO] [1733925084.752349534] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Controller 'fr3_arm_controller' successfully finished
[move_group-3] [INFO] [1733925084.834296039] [moveit_ros.trajectory_execution_manager]: Completed trajectory execution with status SUCCEEDED ...
[move_group-3] [INFO] [1733925084.841459631] [moveit_move_group_default_capabilities.move_action_capability]: Solution was found and executed.
[rviz2-1] [INFO] [1733925084.842150499] [move_group_interface]: Plan and Execute request complete!
``` 
Prova però a metterti in ascolto del topic sottostante ed avviare l'execute del planning:
ros2 topic echo /franka/joint_states
vedi anche te una cosa di questo tipo ?
```
 header:
  stamp:
    sec: 1733924927
    nanosec: 769187933
  frame_id: ''
name:
- fr3_joint1
- fr3_joint3
- fr3_joint2
- fr3_joint4
- fr3_joint5
- fr3_joint6
- fr3_joint7
***position:
- 0.0
- 0.0
- -0.7853981633974483
- -2.356194490192345
- 0.0
- 1.5707963267948966
- 0.7853981633974483
velocity:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0 ***
effort:
- -293.18034137778744
- -63.122798585206624
- -18.065396680383184
- 397.6553533722219
- -25.065307484678925
- -103.28524533673901
- -31.20163361667217
---
header:
  stamp:
    sec: 1733924927
    nanosec: 773182974
  frame_id: ''
name:
- fr3_joint1
- fr3_joint3
- fr3_joint2
- fr3_joint4
- fr3_joint5
- fr3_joint6
- fr3_joint7
position:
- 0.0
- 0.0
- -0.7853981633974483
- -2.356194490192345
- 0.0
- 1.5707963267948966
- 0.7853981633974483
velocity:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
effort:
- -293.18034137778744
- -63.122798585206624
- -18.065396680383184
- 397.6553533722219
- -25.065307484678925
- -103.28524533673901
- -31.20163361667217
---
``` 
Anche a te velocity e position rimangono gli stessi durante e dopo l'execute? Mi sembra strano, dato che su questo topic, da quanto ho studiato, dovrebbe contenere tutte le specifiche di quello che sta facendo il robot (e quindi anche di dov'è). Se guardi, infatti, e quello me lo ricordo perchè ci ho fatto caso, il movimento in Rviz viene effettuato, ma il robot poi resta nella posizione iniziale e non va nella posizione desiderata (quella in arancione per capirci), ma fa solamente vedere il movimento.
Succede anche a te ?
